### ISSUE TITLE
Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982

### ISSUE THREAD

**Issue by AldaneG** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#359]
Hello there,

Would just like to ask if Gorilla Player is compatible with the latest version of GrialKitUI and Xamarin forms?

I tried to run a fresh project from GrialKit and the Gorilla player via the iPhone Simulator and it just stays at the "connected to server screen".

I checked the logs and say a couple of errors including: Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.".

gorilaPlayer.log:
```
{"level":"info","message":"New client.","timestamp":"2019-07-31T16:00:47.286Z"}
{"level":"info","message":"Client info: Platform = iOS; OSVersion = 12.2; Device Model = iPhone; Device Name = iPhone 8 Plus; Idiom = Phone; Screen Type @3x","timestamp":"2019-07-31T16:00:49.496Z"}
{"level":"info","message":"Client info: Mode Sdk (1.5.0.0)","timestamp":"2019-07-31T16:00:49.497Z"}
{"level":"error","message":"Type ValueData is defined multiple times within namespace ProjectFitnessRevolution of assembly ProjectFitnessRevolution, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. Only the last one will prevail.","timestamp":"2019-07-31T16:00:49.522Z"}
{"level":"error","message":"Type FadeDirection is defined multiple times within namespace Xamanimation of assembly Xamanimation, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null. Only the last one will prevail.","timestamp":"2019-07-31T16:00:49.533Z"}
{"level":"error","message":"Could not found assembly Mono.Android with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.535Z"}
{"level":"error","message":"Could not found assembly System.Core with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.536Z"}
{"level":"error","message":"Could not found assembly System.Xml.Linq with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.536Z"}
{"level":"error","message":"Could not found assembly System.Xml with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.536Z"}
{"level":"error","message":"Could not found assembly ProjectFitnessRevolution.Droid with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"Could not found assembly System.Xml with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"Could not found assembly System.Core with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"Could not found assembly Xamarin.iOS with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"Could not found assembly ProjectFitnessRevolution.iOS with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"Could not found assembly FFImageLoading.Platform with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"Could not found assembly FFImageLoading with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"Could not found assembly Newtonsoft.Json with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"Could not found assembly Microsoft.CSharp with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Linq.Expressions with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Linq with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.ObjectModel with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Threading with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Reflection.Emit with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Reflection.Emit.ILGeneration with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Reflection.Emit.Lightweight with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Reflection.TypeExtensions with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"Could not found assembly System.Text.RegularExpressions with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Xml.ReaderWriter with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.IO.FileSystem.Primitives with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Threading.Tasks.Extensions with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Xml.XDocument with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Collections.Concurrent with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Buffers with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Diagnostics.DiagnosticSource with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Security.Cryptography.Primitives with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"Could not found assembly System.Runtime.Numerics with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.Security.Cryptography.Cng with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.Security.Cryptography.OpenSsl with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.Runtime.InteropServices.RuntimeInformation with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.AppContext with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.IO.Compression.ZipFile with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.ComponentModel.TypeConverter with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.ComponentModel with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"Could not found assembly System.Collections.Specialized with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"Could not found assembly System.Runtime.Serialization.Primitives with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"Could not found assembly System.Runtime.Serialization.Formatters with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"Could not found assembly System.Xml.XmlDocument with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"Could not found assembly SkiaSharp with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"Could not found assembly SkiaSharp.Views.Forms with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"warn","message":"Tried to add assembly  Microcharts (version <ANY>) multiple times. Only the first one will be considered.","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"error","message":"Could not found assembly SkiaSharp with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"error","message":"Could not found assembly Xamarin.Essentials with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"error","message":"Could not found assembly System.Numerics.Vectors with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"error","message":"Could not found assembly FFImageLoading.Svg.Platform with version <ANY>. It will be ignored.","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"warn","message":"Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.","timestamp":"2019-07-31T16:00:49.648Z"}
{"level":"warn","message":"Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.","timestamp":"2019-07-31T16:00:49.835Z"}
{"level":"warn","message":"Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.","timestamp":"2019-07-31T16:00:49.835Z"}
{"level":"warn","message":"Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.","timestamp":"2019-07-31T16:00:49.836Z"}
{"level":"warn","message":"Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.","timestamp":"2019-07-31T16:00:49.856Z"}
{"level":"warn","message":"Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.","timestamp":"2019-07-31T16:00:49.864Z"}
{"contextInstanceId":5,"targetId":0,"sampleDataId":2,"level":"info","message":"Notifing issues found (errors: 0, warnings: 0)","timestamp":"2019-07-31T16:00:49.894Z"}
{"level":"info","message":"Bye bye client","timestamp":"2019-07-31T16:11:51.467Z"}
```

gorillaHost.log:
```
{"level":"info","message":"[Server] New client.\n","timestamp":"2019-07-31T16:00:47.286Z"}
{"level":"info","message":"[Server] Client info: Platform = iOS; OSVersion = 12.2; Device Model = iPhone; Device Name = iPhone 8 Plus; Idiom = Phone; Screen Type @3x\n","timestamp":"2019-07-31T16:00:49.497Z"}
{"level":"info","message":"[Server] Client info: Mode Sdk (1.5.0.0)\n","timestamp":"2019-07-31T16:00:49.497Z"}
{"level":"error","message":"[Server] Type ValueData is defined multiple times within namespace ProjectFitnessRevolution of assembly ProjectFitnessRevolution, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. Only the last one will prevail.\n","timestamp":"2019-07-31T16:00:49.522Z"}
{"level":"error","message":"[Server] Type FadeDirection is defined multiple times within namespace Xamanimation of assembly Xamanimation, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null. Only the last one will prevail.\n","timestamp":"2019-07-31T16:00:49.534Z"}
{"level":"error","message":"[Server] Could not found assembly Mono.Android with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.535Z"}
{"level":"error","message":"[Server] Could not found assembly System.Core with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.536Z"}
{"level":"error","message":"[Server] Could not found assembly System.Xml.Linq with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.536Z"}
{"level":"error","message":"[Server] Could not found assembly System.Xml with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"[Server] Could not found assembly ProjectFitnessRevolution.Droid with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"[Server] Could not found assembly System.Xml with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"[Server] Could not found assembly System.Core with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.537Z"}
{"level":"error","message":"[Server] Could not found assembly Xamarin.iOS with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"[Server] Could not found assembly ProjectFitnessRevolution.iOS with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"[Server] Could not found assembly FFImageLoading.Platform with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"[Server] Could not found assembly FFImageLoading with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.538Z"}
{"level":"error","message":"[Server] Could not found assembly Newtonsoft.Json with version <ANY>. It will be ignored.\nerror: Could not found assembly Microsoft.CSharp with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"[Server] Could not found assembly System.Linq.Expressions with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"[Server] Could not found assembly System.Linq with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"[Server] Could not found assembly System.ObjectModel with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Threading with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"[Server] Could not found assembly System.Reflection.Emit with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"[Server] Could not found assembly System.Reflection.Emit.ILGeneration with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Reflection.Emit.Lightweight with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.539Z"}
{"level":"error","message":"[Server] Could not found assembly System.Reflection.TypeExtensions with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"[Server] Could not found assembly System.Text.RegularExpressions with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Xml.ReaderWriter with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"[Server] Could not found assembly System.IO.FileSystem.Primitives with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"[Server] Could not found assembly System.Threading.Tasks.Extensions with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Xml.XDocument with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"[Server] Could not found assembly System.Collections.Concurrent with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"[Server] Could not found assembly System.Buffers with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Diagnostics.DiagnosticSource with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.540Z"}
{"level":"error","message":"[Server] Could not found assembly System.Security.Cryptography.Primitives with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"[Server] Could not found assembly System.Runtime.Numerics with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Security.Cryptography.Cng with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"[Server] Could not found assembly System.Security.Cryptography.OpenSsl with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"[Server] Could not found assembly System.Runtime.InteropServices.RuntimeInformation with version <ANY>. It will be ignored.\nerror: Could not found assembly System.AppContext with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"[Server] Could not found assembly System.IO.Compression.ZipFile with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"[Server] Could not found assembly System.ComponentModel.TypeConverter with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.541Z"}
{"level":"error","message":"[Server] Could not found assembly System.ComponentModel with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"[Server] Could not found assembly System.Collections.Specialized with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"[Server] Could not found assembly System.Runtime.Serialization.Primitives with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Runtime.Serialization.Formatters with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.542Z"}
{"level":"error","message":"[Server] Could not found assembly System.Xml.XmlDocument with version <ANY>. It will be ignored.\nerror: Could not found assembly SkiaSharp with version <ANY>. It will be ignored.\nerror: Could not found assembly SkiaSharp.Views.Forms with version <ANY>. It will be ignored.\nerror: Could not found assembly SkiaSharp with version <ANY>. It will be ignored.\nerror: Could not found assembly Xamarin.Essentials with version <ANY>. It will be ignored.\nerror: Could not found assembly System.Numerics.Vectors with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"warn","message":"[Server] Tried to add assembly  Microcharts (version <ANY>) multiple times. Only the first one will be considered.\n","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"error","message":"[Server] Could not found assembly FFImageLoading.Svg.Platform with version <ANY>. It will be ignored.\n","timestamp":"2019-07-31T16:00:49.543Z"}
{"level":"warn","message":"[Server] Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.\n","timestamp":"2019-07-31T16:00:49.648Z"}
{"level":"warn","message":"[Server] Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.\n","timestamp":"2019-07-31T16:00:49.835Z"}
{"level":"warn","message":"[Server] Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.\nwarn: Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.\n","timestamp":"2019-07-31T16:00:49.836Z"}
{"level":"warn","message":"[Server] Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.\n","timestamp":"2019-07-31T16:00:49.856Z"}
{"level":"warn","message":"[Server] Found assembly Xamarin.Forms.Core but versions are incompatible. Expected 2.0.0.0, existent 3.2.0.839982.\n","timestamp":"2019-07-31T16:00:49.864Z"}
{"level":"info","message":"[Server] Notifing issues found (errors: 0, warnings: 0) contextInstanceId=5, targetId=0, sampleDataId=2\n","timestamp":"2019-07-31T16:00:49.894Z"}
{"level":"info","message":"[Server] Bye bye client\n","timestamp":"2019-07-31T16:11:51.468Z"}
```

**Comment by attrib75** [comment]
I'm seeing the same thing, and Gorilla player is not working as it used to with the newer Visual Studio and Xamarin

**Comment by ForteUnited** [comment]
I'm seeing the exact same thing in my logs and then in my player I get very generic "Error loading XAML." "Number of parameters specified does not match the expected number." 

I have even tested this on a new blank content page where the only element is a label that says "Welcome to Xamarin.Forms" and I get the same error.

Could really use some help here.

**Comment by LeoHere** [comment]
@ForteUnited the 'Number of parameters specified does not match the expected number.' error is fixed in Gorilla SDK Nuget 1.5.4. 

@AldaneG yes, Gorilla is compatible with the latest version of Grial UI Kit and the latest version of Xamarin Forms.

**Comment by ForteUnited** [comment]
> @ForteUnited the 'Number of parameters specified does not match the expected number.' error is fixed in Gorilla SDK Nuget 1.5.4.
> 
> @AldaneG yes, Gorilla is compatible with the latest version of Grial UI Kit and the latest version of Xamarin Forms.

Sweet! I'll take a look. Thanks!

**Comment by ForteUnited** [comment]
Now I get an error that says

"Error occurred while loading C:\<blahblahblah>\AboutPage.xaml (error message: Cannot read property 'tagReplacement' of null)."

**Comment by ForteUnited** [comment]
Here is more from my gorillaHost.log 

{"level":"error","message":"[Server] Xaml processing error Summary:\"Error loading SignUpPage.xaml (Target XAML).\"; Message:\"Error occurred while loading C:\\<BLAHBLAHBLAHREMOVED>\\SignUpPage.xaml (error message: Cannot read property 'tagReplacement' of null).\" processingIssue=true, issueType=error, position=null, area=Xaml, scope=Req, name=TypeError, message=Cannot read property 'tagReplacement' of null, stack=TypeError: Cannot read property 'tagReplacement' of null\n    at Object.onOpenTag (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\app\\server\\post\\TagReplacement.js:15:47)\n    at Object._applyTransformations (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\app\\server\\post\\PostTransformation.js:51:53)\n    at Object.transform (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\app\\server\\post\\PostTransformation.js:9:22)\n    at Object.processXamlObject (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\app\\server\\DependencyManager.js:240:23)\n    at Object.<anonymous> (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\app\\server\\DependencyManager.js:142:26)\n    at Object.<anonymous> (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\app\\server\\XamlStore.js:34:25)\n    at Object.tryCatcher (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\node_modules\\bluebird\\js\\main\\util.js:26:23)\n    at Promise._settlePromiseFromHandler (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\node_modules\\bluebird\\js\\main\\promise.js:510:31)\n    at Promise._settlePromiseAt (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\node_modules\\bluebird\\js\\main\\promise.js:584:18)\n    at Async._drainQueue (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\node_modules\\bluebird\\js\\main\\async.js:128:12)\n    at Async._drainQueues (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\node_modules\\bluebird\\js\\main\\async.js:133:10)\n    at Immediate.Async.drainQueues (C:\\Program Files\\Gorilla Player\\resources\\app.asar\\node_modules\\bluebird\\js\\main\\async.js:15:14)\n    at runCallback (timers.js:651:20)\n    at tryOnImmediate (timers.js:624:5)\n    at processImmediate [as _immediateCallback] (timers.js:596:5), contextInstanceId=2, targetId=1, sampleDataId=1\r\n","timestamp":"2019-10-31T00:36:53.588Z"}

**Comment by LeoHere** [comment]
@ForteUnited. It seems to be a bug introduced in 1.5.4.0.  Do you have a `Gorilla.json` file in yours.net Standard project? if not can you try to add it at the root of your project with build action `None`. Add an empty JSON object as its content (i.e `{}`). 

Let me know if that works as a workaround to the problem.

**Comment by ForteUnited** [comment]
Seems to be working now! Great tool!
