### ISSUE TITLE
Login not work in new Gorilla player account 

### ISSUE THREAD

**Issue by maverix72** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#374]
Hi,

After downloading  Gorilla player Windows Version 1.5.5.0 and after creating a new verified account, starting software and after entering the user and password, authentication fails. My account is: [removed email]
![Screenshot_27](https://user-images.githubusercontent.com/20167963/74343408-4aecca00-4dab-11ea-9edc-e3a021208488.png)

**Comment by srdosramos** [comment]
Hi I have the same issue, cant log in to Gorilla Player,

After looking on the logs found that the certificated for the endpoint is expired. 

here are the logs;

{"level":"info","message":"[Analytics] Setting user 3297bf50-4db0-11ea-8708-e17b87afd717 (generated=true)","timestamp":"2020-02-12T16:25:48.228Z"}
{"level":"error","message":"Unable invoke checkForUpdate service. Error \"certificate has expired\" occurred (Error: certificate has expired\n    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:603:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)).","timestamp":"2020-02-12T16:25:49.713Z"}
{"level":"error","message":"Check for update: Can't get the last known version from the server","timestamp":"2020-02-12T16:25:49.714Z"}
{"level":"info","message":"Signin endpoint: https://www.uxdivers.com/api/v1/login","timestamp":"2020-02-12T16:26:23.742Z"}
{"level":"error","message":"Failed authenticating user. Status -1, error message <No error reported>","timestamp":"2020-02-12T16:26:24.959Z"}

the certificate for this endpoint https://www.uxdivers.com/api/v1/login has expired yesterday

**Comment by jpbrocca** [comment]
Hello @maverix72 and @maverix72,
sorry about this issue.

It should be fixed now.
Could you give it a try and let me know?

Regards and thanks
JP

**Comment by maverix72** [comment]
Hello JPBrocca,
now Gorilla Player start and login it’s Ok,
but when I try to reopen application the maessage “Could not initialize Gorilla. Port 9014 in Use” appiar and application not start.

I start Gorilla in Win 10 Pro

Thanks
Filippo



Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: jpbrocca<mailto:notifications@github.com>
Inviato: mercoledì 12 febbraio 2020 18:13
A: UXDivers/Gorilla-Player-Support<mailto:Gorilla-Player-Support@noreply.github.com>
Cc: maverix72<mailto:maverix72@hotmail.it>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [UXDivers/Gorilla-Player-Support] Login not work in new Gorilla player account (#374)


Hello @maverix72<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaverix72&data=02%7C01%7C%7Ccafd2d108d264ed4e87808d7afded579%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637171243899644836&sdata=n%2BHEj12dvtsF07ZnbW%2B7YrnxYhBr99B7BbhPtqIqtbk%3D&reserved=0> and @maverix72<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaverix72&data=02%7C01%7C%7Ccafd2d108d264ed4e87808d7afded579%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637171243899644836&sdata=n%2BHEj12dvtsF07ZnbW%2B7YrnxYhBr99B7BbhPtqIqtbk%3D&reserved=0>,
sorry about this issue.

It should be fixed now.
Could you give it a try and let me know?

Regards and thanks
JP

**Comment by fariduca** [comment]
Hello @jpbrocca! Can you please help? I'm facing the same issue. I can't log in. 

Here are logs:

{"level":"error","message":"Error occurred while reading the registry key \\Software\\Wow6432Node\\Microsoft\\VisualStudio\\15.0, message: QUERY command exited with code 1:\n\nERROR: The system was unable to find the specified registry key or value., stack: Error\n    at mkErrorMsg (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\node_modules\\winreg\\lib\\registry.js:111:12)\n    at ChildProcess.<anonymous> (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\node_modules\\winreg\\lib\\registry.js:459:10)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:885:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5).","timestamp":"2021-02-08T10:56:01.771Z"}
{"level":"info","message":"Starting Gorilla App...","timestamp":"2021-02-08T11:04:24.982Z"}
{"level":"error","message":"Error reading license file ENOENT: no such file or directory, open 'C:\\Users\\faridun.mamadbekov\\.gorilla\\license' Error: ENOENT: no such file or directory, open 'C:\\Users\\faridun.mamadbekov\\.gorilla\\license'\n    at Object.fs.openSync (fs.js:558:18)\n    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)\n    at Object.fs.readFileSync (fs.js:468:33)\n    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)\n    at Object.verifyLicense (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\app\\server\\LicenseHelper.js:131:30)\n    at Object.getCurrentUser (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\app\\server\\LicenseHelper.js:104:18)\n    at Object.currentUser (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\app\\gorillaProxy.js:42:27)\n    at C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\app\\background.js:113:14\n    at Object.<anonymous> (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\app\\background.js:995:2)\n    at Object.<anonymous> (C:\\Users\\faridun.mamadbekov\\AppData\\Local\\Programs\\Gorilla Player\\resources\\app.asar\\app\\background.js:997:3)","timestamp":"2021-02-08T11:04:25.086Z"}
{"level":"info","message":"[Analytics] Setting user 3ec46700-66d8-11eb-9e4a-b74e0096e5b0 (generated=true)","timestamp":"2021-02-08T11:04:25.086Z"}
{"level":"error","message":"Unable invoke checkForUpdate service. Error \"certificate has expired\" occurred (Error: certificate has expired\n    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:603:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)).","timestamp":"2021-02-08T11:04:27.156Z"}
{"level":"error","message":"Check for update: Can't get the last known version from the server","timestamp":"2021-02-08T11:04:27.157Z"}
{"level":"info","message":"Signin endpoint: https://www.uxdivers.com/api/v1/login","timestamp":"2021-02-08T11:06:11.559Z"}
{"level":"error","message":"Failed authenticating user. Status -1, error message <No error reported>","timestamp":"2021-02-08T11:06:12.189Z"}

**Comment by kakarottobcn** [comment]
Hi

I am facing exactly the same issue as fariduca with Gorilla Player 1.5.5 and win10. Any suggestions? 

Thanks
